### ISSUE TITLE
NPM package doesn't work on client

### ISSUE THREAD

**Issue by patoncrispy** [stimulsoft/Reports.JS#1]
Due to multiple filesystem dependencies (`fs`, `tls`, `dgram`, etc.), the NPM package does not work in the browser.

I'm using Webpack as my build tool and importing the raw javascript files just results in build errors as `stimulsoft.designer.js` deletes local variables, which is not allowed in strict mode.

**Comment by kubekin2** [comment]
We know about this problem. We can help if you request our special version.
Thank you.

**Comment by Inhabe** [comment]
How can i request this special version? got simular situation working with webpack and tried to import it.
