### ISSUE TITLE
Make the dependencies optional

### ISSUE THREAD

**Issue by egandro** [stimulsoft/Reports.JS#5]
This are a very heavy load of dependencies:

		"mssql" : "^3.1.2",
		"mysql" : "^2.10.2",
		"node-firebird" : "^0.7.2",
		"opentype.js" : "^0.6.1",
		"pg" : "^4.5.1",
		"rgbcolor" : "^0.0.4",
		"stackblur" : "^1.0.0",
		"sync-request": "^3.0.1",
		"jszip": "^2.6.1"

Can you make them optional or create a production package or a hin to the user to deep copy the (unlocked) version to the project.

Thank you.

**Comment by AlexKulikow** [comment]
Hello,

There are no such options, if you do not use the functions that require the data of the library, you can remove them.
