### ISSUE TITLE
Variables are not being passed to the report

### ISSUE THREAD

**Issue by gitstc** [stimulsoft/Reports.JS#7]
I have written the following code to load a .mrt file, pass a variable to it and render a report which is then saved in a PDF file. The problem is that the variable that I am passing is not being detected in the report. I noticed that in the .NET library, we need to call the report.Compile() after setting the variables, but there is no .compile method documented for the JS library.
This code will be running in a NodeJS Express server.

`var report = new Stimulsoft.Report.StiReport();
var reportTemplate = fs.readFileSync('orderDetails.mrt');
report.load(reportTemplate);
report.dictionary.variables.getByName("OrderID").valueObject = 123;
report.render();
var pdfData = report.exportDocument(Stimulsoft.Report.StiExportFormat.Pdf);
var buffer = new Buffer(pdfData, "utf-8");
fs.writeFileSync('ordersReport.pdf'), buffer);`

Please advise

**Comment by dewaunayers** [comment]
Hi @gitstc, I don't know if you figured out the problem for yourself, but I'll leave an answer here anyway. When I logged the getByName() method to the console there was no "valueObject" property, but there is a "val" property available to change.

The only thing you need to change in your code is 

`report.dictionary.variables.getByName("OrderID").valueObject = 123`

to

`report.dictionary.variables.getByName("OrderID").val = 123`

and it should work just fine! :)
